"""Audit fix C5 (Fable finding V5, 10 Oct 2026, instruction_combined_
10oct.md PART C): reverse_dcf_engine's own bisection used to compound
a candidate growth rate FLAT across the entire horizon - but the
forward model (fcf_valuation_engine.dcf_intrinsic_value()'s own
"Stage 1"/"Growth-path option E" loop) fades from that rate down to
a market-cap-tiered end_rate over years 6-growth_years (flat years
1-5, or the whole horizon if the rate is already at/below end_rate).
The reverse solve was therefore answering "what FLAT rate justifies
this price", a different question from what the forward model (and
the on-screen Intrinsic Value it drives) actually assumes - "Implied
Growth %" and "Model Growth %" could legitimately disagree even when
both were correctly computed, purely from using two different growth
PATH shapes.

Fix: _dcf_value_for_growth()/_solve_growth() now take the SAME
end_rate (growth_end_rate_for(info, currency), floored at the
perpetual rate) the forward model uses, and replicate its EXACT fade
formula. compute() computes this once per call, same as the forward
model computes it once per DCF run.

Expected effect (owner's own report): "Implied Growth %" changes on
every DCF row whose solved rate ends up above end_rate (the fade
actually engages) - IV/MOS themselves are completely unaffected,
since dcf_intrinsic_value() (the function that actually produces the
on-screen Intrinsic Value/MOS) is untouched by this commit; only
reverse_dcf_engine.py changed.

Run: python3 tests/test_audit_c5_reverse_dcf_fade_schedule.py
"""
import inspect
import os
import sys
from unittest import mock

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import fcf_valuation_engine as fve
import reverse_dcf_engine as rdcf

passed = 0
failed = 0


def check(label, condition):
    global passed, failed
    if condition:
        passed += 1
        print(f"  OK: {label}")
    else:
        failed += 1
        print(f"  FAIL: {label}")


# ======================================================================
# CHECK 1: _dcf_value_for_growth()/_solve_growth() direct unit tests -
# the faded formula actually differs from a flat one, and recovering
# the SAME flat growth rate still works when end_rate is set so high
# the fade condition never fires (growth_rate > end_rate is always
# False) - a built-in way to compare "old" (flat) vs "new" (faded)
# using the identical function.
# ======================================================================
FCF, D, P, YEARS, END_RATE = 5.0, 0.08, 0.02, 10, 0.06

# A price generated by a flat 12% (end_rate=999 forces fade=False for
# any realistic candidate, reproducing the OLD pre-fix formula exactly).
price_at_flat_12pct = rdcf._dcf_value_for_growth(FCF, 0.12, D, P, YEARS, end_rate=999.0)

g_old_flat, capped_old = rdcf._solve_growth(FCF, price_at_flat_12pct, D, P, YEARS, end_rate=999.0)
check("the flat-equivalent solve (end_rate forced out of reach) "
      "recovers the original 12% within the function's own 0.01% "
      "bisection tolerance",
      abs(g_old_flat - 0.12) < 0.001 and capped_old is None)

g_new_faded, capped_new = rdcf._solve_growth(FCF, price_at_flat_12pct, D, P, YEARS, end_rate=END_RATE)
check("with the REAL end_rate (0.06) and the SAME target price, the "
      "faded solve requires a HIGHER starting growth rate than the "
      "flat solve - fading down after year 5 needs more upfront "
      "growth to reach the identical price",
      g_new_faded > g_old_flat and capped_new is None)

print(f"  [mechanism] same target price (${price_at_flat_12pct:.2f}): flat-equivalent "
      f"solve g*={g_old_flat:.4f} ({g_old_flat:.1%}) vs faded (end_rate=6%) solve "
      f"g*={g_new_faded:.4f} ({g_new_faded:.1%}) - {(g_new_faded - g_old_flat) / g_old_flat:+.1%} relative")

# A growth rate AT or BELOW end_rate must behave identically whether
# or not the fade mechanism exists - no fade ever applies either way.
_v_flat_low = rdcf._dcf_value_for_growth(FCF, 0.03, D, P, YEARS, end_rate=999.0)
_v_faded_low = rdcf._dcf_value_for_growth(FCF, 0.03, D, P, YEARS, end_rate=END_RATE)
check("a candidate growth rate (3%) already below end_rate (6%) gives "
      "the IDENTICAL value whether end_rate is real or forced out of "
      "reach - the fade never engages below its own target",
      abs(_v_flat_low - _v_faded_low) < 1e-9)

# growth_years <= 5 must also never fade (same guard as the forward
# model - "every year is in the flat window").
_v_short_flat = rdcf._dcf_value_for_growth(FCF, 0.20, D, P, 5, end_rate=999.0)
_v_short_faded = rdcf._dcf_value_for_growth(FCF, 0.20, D, P, 5, end_rate=END_RATE)
check("growth_years=5 (no fade stage at all) gives the identical "
      "value regardless of end_rate - matches the forward model's "
      "own 'growth_years <= 5' guard",
      abs(_v_short_flat - _v_short_faded) < 1e-9)


# ======================================================================
# CHECK 2: end-to-end through compute() - a real DCF-shaped fixture,
# mocking only dcf_intrinsic_value() itself (the forward model is not
# being tested here - fcf_valuation_engine.py is untouched by this
# commit) to supply a controlled fcf_per_share/discount_rate/
# perpetual_rate, same pattern as this repo's own established
# mocking convention for this exact function.
# ======================================================================
_INFO = {"marketCap": 500_000_000, "currency": "USD"}
_META = {
    "fcf_per_share_used": FCF, "discount_rate_used": D, "perpetual_rate_used": P,
    "defaulted": False,
}

with mock.patch.object(rdcf, "dcf_intrinsic_value", return_value=(999.0, 0.12, _META)):
    _res = rdcf.compute(
        "FIXTURE", price_at_flat_12pct, info=_INFO, currency="USD", growth_years=YEARS,
    )

check("compute() end to end: ok=True, model_growth passed straight "
      "through unchanged from dcf_intrinsic_value()'s own return",
      _res["ok"] is True and _res["model_growth"] == 0.12)
check("compute()'s own implied_growth matches the direct _solve_growth() "
      "result above - the SAME faded mechanism, wired correctly",
      abs(_res["implied_growth"] - round(g_new_faded, 4)) < 0.0005)
check("implied_growth (faded) now DIFFERS from model_growth (0.12) for "
      "this fixture - before this fix, a price built from a flat 12% "
      "solve would have recovered implied_growth ~= model_growth "
      "(both flat); now they correctly diverge because the PRICE "
      "implies more aggressive early growth under a fading path",
      abs(_res["implied_growth"] - _res["model_growth"]) > 0.01)


# ======================================================================
# CHECK 3: IV/MOS are completely unaffected by this commit - source
# inspection confirms fcf_valuation_engine.dcf_intrinsic_value() itself
# (the function that actually produces the on-screen Intrinsic Value/
# MOS) is still imported, never reimplemented or monkeypatched by
# reverse_dcf_engine.py - only the module's OWN bisection helpers
# changed.
# ======================================================================
_rdcf_src = inspect.getsource(rdcf)
check("reverse_dcf_engine.py still imports (never reimplements) "
      "fcf_valuation_engine.dcf_intrinsic_value() for the actual DCF "
      "- IV/MOS are computed exactly as before this fix",
      "from fcf_valuation_engine import dcf_intrinsic_value" in _rdcf_src)
check("growth_end_rate_for is now also imported - the new piece this "
      "fix adds, nothing else from fcf_valuation_engine",
      "growth_end_rate_for" in _rdcf_src)


# ======================================================================
# CHECK 4: capped low/high bisection bounds still work correctly with
# the faded value function - a price far outside what the band can
# produce at all.
# ======================================================================
_v_at_max = rdcf._dcf_value_for_growth(FCF, rdcf.GROWTH_MAX, D, P, YEARS, END_RATE)
_v_at_min = rdcf._dcf_value_for_growth(FCF, rdcf.GROWTH_MIN, D, P, YEARS, END_RATE)
g_hi, capped_hi = rdcf._solve_growth(FCF, _v_at_max * 2, D, P, YEARS, END_RATE)
g_lo, capped_lo = rdcf._solve_growth(FCF, _v_at_min / 2 if _v_at_min > 0 else -1, D, P, YEARS, END_RATE)
check("a price above what GROWTH_MAX can produce (even faded) caps "
      "at GROWTH_MAX, flagged 'high'",
      g_hi == rdcf.GROWTH_MAX and capped_hi == "high")
check("a price at/below what GROWTH_MIN can produce caps at "
      "GROWTH_MIN, flagged 'low'",
      g_lo == rdcf.GROWTH_MIN and capped_lo == "low")

print()
print(f"PASS={passed} FAIL={failed}")
sys.exit(1 if failed else 0)
